In [2]:
import numpy as np
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.
s=np.random.random((5,5))
print(s)
d=s.max()
print(d)
m=s.min()
print(m)

[[0.52592662 0.19902798 0.8090349  0.49896873 0.28888705]
 [0.86852066 0.78926043 0.44248556 0.8123886  0.79297494]
 [0.56805889 0.94759752 0.83447291 0.6207498  0.01949239]
 [0.36157881 0.83027542 0.35449042 0.50699677 0.19897302]
 [0.60395474 0.9758004  0.00627433 0.59843206 0.35491436]]
0.9758003954373783
0.006274328535848972


In [3]:
# Write a NumPy program to compute the multiplication of two given matrixes. Sample Matrix: [[1, 0], [0, 1]] [[1, 2], [3, 4]]

f=[[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

print(f)
print(q)

d=np.dot(f,q)
d

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]


array([[1, 2],
       [3, 4]])

In [4]:
# Use of around() function: returns a decimal value rounded to a desired position of the decimal

a = np.array([12.202, 90.23120, 123.020, 23.202]) 
v=np.around(a,2)
v=np.around(a,3)
v

array([ 12.202,  90.231, 123.02 ,  23.202])

In [5]:
# Find the number of occurrences of a sequence in a NumPy array

arr= np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
d=repr(arr).count('4')
d

5

In [6]:
# create an array of 20 linearly spaced point between 0 to 1

h=np.linspace(0,1)
h

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])